[project]
name = "hello-world-genai"
version = "0.1.0"
description = "FastAPI application with Bigram Text Generation and Word Embeddings"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.124.0",
    "jupyter>=1.1.1",
    "pydantic>=2.12.5",
    "spacy>=3.7.0",
    "scikit-learn>=1.4.0",
]
